
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class frmHome extends javax.swing.JFrame {
    private String playerName;
    /**
     * Creates new form frmHome
     */
    public frmHome(String name) {
        initComponents();
        UITheme.apply(this);
        this.playerName = name;
        setTitle("Trang chủ - Người chơi: " + name);
        setLocationRelativeTo(null); // Căn giữa form
    }

    public frmHome() {
        initComponents();
        UITheme.apply(this);
        setTitle("Trang chủ - Chưa có tên người chơi");
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoiMay = new javax.swing.JButton();
        btnVoiban = new javax.swing.JButton();
        btnNgaunhien = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoiMay.setText("Đấu với máy");
        btnVoiMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoiMayActionPerformed(evt);
            }
        });

        btnVoiban.setText("Đấu với bạn");
        btnVoiban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoibanActionPerformed(evt);
            }
        });

        btnNgaunhien.setText("Đấu ngẫu nhiên");
        btnNgaunhien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgaunhienActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnVoiMay)
                .addGap(39, 39, 39)
                .addComponent(btnVoiban)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnNgaunhien)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoiban)
                    .addComponent(btnNgaunhien)
                    .addComponent(btnVoiMay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát không?", 
                                                    "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnVoiMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoiMayActionPerformed
        JOptionPane.showMessageDialog(this, "Chế độ đấu với máy đang được phát triển...");
        frmDauvoimay frm = new frmDauvoimay(playerName);
        frm.setVisible(true);

        // Ẩn form hiện tại (trang chủ)
        this.dispose();
    }//GEN-LAST:event_btnVoiMayActionPerformed

    private void btnVoibanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoibanActionPerformed
        String[] options = {"Tạo phòng", "Tham gia phòng", "Hủy"};
        int choice = JOptionPane.showOptionDialog(
            this,
            "Chọn hành động bạn muốn:",
            "Đấu với bạn",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            options,
            options[0]
        );

        switch (choice) {
            case 0: // ✅ Tạo phòng
                String maPhong = JOptionPane.showInputDialog(this, 
                    "Nhập mã phòng bạn muốn tạo:\n(Mã phòng phải có ít nhất 4 ký tự)", 
                    "Tạo phòng mới");

                if (maPhong == null || maPhong.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã phòng!");
                    return;
                }

                // Kiểm tra độ dài mã phòng
                if (maPhong.trim().length() < 4) {
                    JOptionPane.showMessageDialog(this, "Mã phòng phải có ít nhất 4 ký tự!");
                    return;
                }

                // Kiểm tra phòng đã tồn tại chưa
                if (PhongManager.maPhongHienTai != null && PhongManager.maPhongHienTai.equals(maPhong.trim())) {
                    JOptionPane.showMessageDialog(this, "Mã phòng này đã được sử dụng!");
                    return;
                }

                // Lưu mã phòng vào bộ nhớ tĩnh
                PhongManager.maPhongHienTai = maPhong.trim();
                PhongManager.coNguoiThamGia = false;

                JOptionPane.showMessageDialog(this,
                        "Phòng của bạn đã được tạo!\nMã phòng: " + maPhong.trim(),
                        "Tạo phòng thành công", JOptionPane.INFORMATION_MESSAGE);

                // Mở frmDauvoiban (người tạo phòng)
                frmDauvoiban frmTaoPhong = new frmDauvoiban();
                frmTaoPhong.setTitle("Đấu với bạn - Phòng #" + maPhong.trim() + " (Chủ phòng)");
                frmTaoPhong.setVisible(true);

                this.dispose();
                break;

            case 1: // ✅ Tham gia phòng
                String maNhap = JOptionPane.showInputDialog(this, "Nhập mã phòng:");

                if (maNhap == null || maNhap.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã phòng!");
                    return;
                }

                // Kiểm tra phòng có tồn tại không
                if (PhongManager.maPhongHienTai == null) {
                    JOptionPane.showMessageDialog(this, "Hiện chưa có phòng nào được tạo!");
                    return;
                }

                if (!maNhap.equals(PhongManager.maPhongHienTai)) {
                    JOptionPane.showMessageDialog(this, "Phòng không tồn tại hoặc mã sai!");
                    return;
                }

                if (PhongManager.coNguoiThamGia) {
                    JOptionPane.showMessageDialog(this, "Phòng này đã đủ người!");
                    return;
                }

                // ✅ Người chơi 2 tham gia thành công
                PhongManager.coNguoiThamGia = true;

                JOptionPane.showMessageDialog(this, "Tham gia phòng thành công!");

                frmDauvoiban frmThamGia = new frmDauvoiban();
                frmThamGia.setTitle("Đấu với bạn - Phòng #" + maNhap + " (Người tham gia)");
                frmThamGia.setVisible(true);

                this.dispose();
                break;

            default:
                break;
        }
    }//GEN-LAST:event_btnVoibanActionPerformed

    private void btnNgaunhienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgaunhienActionPerformed
        frmDaungaunhien frm = new frmDaungaunhien();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNgaunhienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNgaunhien;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnVoiMay;
    private javax.swing.JButton btnVoiban;
    // End of variables declaration//GEN-END:variables
}
